### ISSUE TITLE
When using a wooden bucket on a cauldron the bucket turns into a iron bucket

### ISSUE THREAD

**Issue by DaisyTheMage** [satyrnidae/new-buckets-fabric#1]
If you use a wooden bucket to fill a cauldron then you will have an empty iron bucket

**Reproduction Steps**
1. Go to a cauldron with a filled wooden bucket
2. Interact with the cauldron
3. Your wooden bucket will now be made of iron

**Comment by satyrnidae** [comment]
ah, i knew i forgot to test _something_
